#!/bin/sh

set -e
set -u

ECHO=/bin/echo

# Optionally write registration json file.
if [ -n "${CERTHUB_ACME_DNS_REGISTRATION:-}" ]; then
    CERTHUB_ACME_DNS_REGISTRATION_FILE="${CERTHUB_ACME_DNS_REGISTRATION_FILE:-${HOME}/acme-dns-registration.json}"

    if [ ! -e "${CERTHUB_ACME_DNS_REGISTRATION_FILE}" ]; then
        (umask 077 && ${ECHO} "${CERTHUB_ACME_DNS_REGISTRATION}" > "${CERTHUB_ACME_DNS_REGISTRATION_FILE}")
    fi
fi
