#!/bin/sh
#
# certhub-acme-generator - Systemd generator for certhub .acme units.

set -e
set -u

# Required binaries
BASENAME=/usr/bin/basename
DIRNAME=/usr/bin/dirname
READLINK=/bin/readlink
ECHO=/bin/echo
LN=/bin/ln
MKDIR=/bin/mkdir


# Print usage message and exit.
usage() {
    ${ECHO} "${0}: normal-dir [early-dir] [late-dir]"
    return 1
}

certhub_acme_generator() {
    SOURCE_UNIT_DIR="${1}"
    CERTHUB_ACME_CLIENT="${2}"
    SYSTEM_UNIT_DIR="${3}"
    DEST_UNIT_DIR="${4}"
    shift 4

    for UNIT_FILE in "${SOURCE_UNIT_DIR}"/*".${CERTHUB_ACME_CLIENT}"; do
        if stat "${UNIT_FILE}" >/dev/null 2>&1; then
            CERTHUB_CERT_SLUG="$(${BASENAME} "${UNIT_FILE}" ".${CERTHUB_ACME_CLIENT}")"
            ${MKDIR} -p "${DEST_UNIT_DIR}/paths.target.wants"
            ${LN} -s "${SYSTEM_UNIT_DIR}/certhub-${CERTHUB_ACME_CLIENT}-run@.path" "${DEST_UNIT_DIR}/paths.target.wants/certhub-${CERTHUB_ACME_CLIENT}-run@${CERTHUB_CERT_SLUG}.path"
            ${MKDIR} -p "${DEST_UNIT_DIR}/timers.target.wants"
            ${LN} -s "${SYSTEM_UNIT_DIR}/certhub-cert-expiry@.timer" "${DEST_UNIT_DIR}/timers.target.wants/certhub-cert-expiry@${CERTHUB_CERT_SLUG}.timer"
        fi
    done
}

if [ "${#}" -gt 0 ] && [ "${1:-}" != "-h" ] && [ "${1:-}" != "--help" ]; then
    SOURCE_UNIT_DIR="${CERTHUB_UNIT_DIR:-/etc/certhub/systemd}"
    SYSTEM_UNIT_DIR="$(${READLINK} -f "$(${DIRNAME} "$0")"/../system)"
    certhub_acme_generator "${SOURCE_UNIT_DIR}" certbot "${SYSTEM_UNIT_DIR}" "${1}"
    certhub_acme_generator "${SOURCE_UNIT_DIR}" lego "${SYSTEM_UNIT_DIR}" "${1}"
    certhub_acme_generator "${SOURCE_UNIT_DIR}" dehydrated "${SYSTEM_UNIT_DIR}" "${1}"
else
    usage
fi
