#!/bin/sh
#
# certhub-send-generator - Systemd generator for certhub .send units.

set -e
set -u

# Required binaries
BASENAME=/usr/bin/basename
DIRNAME=/usr/bin/dirname
READLINK=/bin/readlink
ECHO=/bin/echo
LN=/bin/ln
MKDIR=/bin/mkdir


# Print usage message and exit.
usage() {
    ${ECHO} "${0}: normal-dir [early-dir] [late-dir]"
    return 1
}

certhub_send_generator() {
    SOURCE_UNIT_DIR="${1}"
    SYSTEM_UNIT_DIR="${2}"
    DEST_UNIT_DIR="${3}"
    shift 3

    for UNIT_FILE in "${SOURCE_UNIT_DIR}"/*".send"; do
        if stat "${UNIT_FILE}" >/dev/null 2>&1; then
            CERTHUB_CERT_SLUG="$(${BASENAME} "${UNIT_FILE}" ".send")"
            ${MKDIR} -p "${DEST_UNIT_DIR}/paths.target.wants"
            ${LN} -s "${SYSTEM_UNIT_DIR}/certhub-cert-send@.path" "${DEST_UNIT_DIR}/paths.target.wants/certhub-cert-send@${CERTHUB_CERT_SLUG}.path"
        fi
    done
}

if [ "${#}" -gt 0 ] && [ "${1:-}" != "-h" ] && [ "${1:-}" != "--help" ]; then
    SOURCE_UNIT_DIR="${CERTHUB_UNIT_DIR:-/etc/certhub/systemd}"
    SYSTEM_UNIT_DIR="$(${READLINK} -f "$(${DIRNAME} "$0")"/../system)"
    certhub_send_generator "${SOURCE_UNIT_DIR}" "${SYSTEM_UNIT_DIR}" "${1}"
else
    usage
fi
