---
name: Run integration tests

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      LEXICON_DIGITALOCEAN_TOKEN:
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-sphinx python3-sphinx-rtd-theme python3-sphinxcontrib.plantuml

      - name: Prepare integration tests
        run: |
          make dist
          make -C integration-test images

      - name: Run integration tests
        run: make -C integration-test all
