---
name: Integration Tests (Pull Request)

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/do-lint.yml

  unit-test:
    uses: ./.github/workflows/do-unit-test.yml
