---
name: Publish Rolling Image (Push develop)

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  lint:
    uses: ./.github/workflows/do-lint.yml

  unit-test:
    uses: ./.github/workflows/do-unit-test.yml
